function rolarD100() {
    // Gera um número aleatório de 1 a 100
    var resultado = Math.floor(Math.random() * 100) + 1;

    // Mapeia os resultados para frases correspondentes
    var frases = {
        1: 'Uma intensa atividade cerebral extraplanar chega até você. Você ganha conhecimento muito avançado para os padrões artonianos. Você fica atordoado por 1d6 rodadas, mas após isso recebe um bônus permanente de +1 em Inteligência, Sabedoria ou Carisma (escolha aleatoriamente).',
    2: 'A alça do seu escudo se desprende. Você pode deixar o escudo cair e não sofrer penalidades, ou lutar desta forma e sofrer uma penalidade de –2 em jogadas de ataque e de –1 em CA.',
    3: 'Subitamente, você nota que está muito fora de forma, e lembra que passou a última semana enfurnado na taverna, comendo e bebendo demais. Você fica exausto até o fim do combate.',
    4: 'Momento desastroso: você é atingido por uma onda súbita de azar e incompetência generalizada. Role duas vezes nesta tabela.',
    5: 'Em um movimento louco que irá entrar para os anais dos manuais de combate, você embainha sua arma sem querer.',
    6: 'Você tropeça em alguma coisa e cai de cara no chão. Com o rosto amassado, você sofre 2 pontos de dano em Carisma, além de ficar caído.',
    7: 'Cheiro ruim: quem foi? Não importa, você fica enjoado por 1d3 rodadas. Durante este tempo, você também sofre uma penalidade de –2 em testes de Fortitude.',
    8: 'Ataque de riso! Você subitamente acha muita graça de algo, sofrendo os efeitos da magia riso histérico por 1d4 rodadas. Aposto que na mesa de jogo o único que não está rindo é você!',
    9: 'Cãibra na perna esquerda: seu deslocamento é reduzido à metade. Caso você não tenha a perna direita, cai no chão. Se estiver na água, sofre –4 em testes para nadar.',
    10: 'Uma velha ferida se abre... De novo! Você perde 5 PV e fica abalado por 1d4 rodadas.',
    11: 'Casca de banana: um clássico! Você cai de costas no chão e perde 1d6 PV.',
    12: 'Ops! Você pisa em um inseto grande e nojento. Perca uma rodada tirando a gosma da bota ou sofra uma penalidade de –1 em todas as jogadas de ataque e testes de resistência até fazer isso.',
    13: 'Presságio de morte... A sua! O próximo golpe que você sofrer será um acerto crítico, ou a próxima magia que lhe causar dano causará o dobro do dano normal.',
    14: 'Uma onda de energia negativa atinge o campo de batalha, fazendo com que um inimigo que já havia sido derrotado erga-se como um zumbi! O inimigo tem as mesmas estatísticas, mas sem habilidades especiais.',
    15: 'Uma área de Tormenta aparece debaixo dos seus pés! Ou apenas um fenômeno arcano parecido — mas você não vai ficar aqui para conferir. Faça um teste de Reflexos (CD 20). Em caso de falha, você sofre 6 pontos de dano em todas as habilidades. Contudo, você recebe um talento da Tormenta escolhido pelo mestre.',
    16: 'Você sente uma fisgada no braço. Penalidade de –1 na CA até sua próxima rodada.',
    17: 'Fenômeno mágico! O céu fica rosa, deuses passam voando entre as nuvens ou chovem sapos. Todos no combate ficam olhando, e perdem sua ação na próxima rodada. Após a pausa, todos rolam iniciativa novamente.',
    18: 'Cãibra no pescoço: penalidade de –4 em testes de Percepção e Reflexos por 1d4 rodadas.',
    19: 'Fenômeno climático imprevisível. Um relâmpago atinge seu braço erguido no meio do golpe. Você sofre 6d6 pontos de dano de eletricidade.',
    20: 'Você deixa cair seu escudo.',
    21: 'Você se descuida e abre sua guarda! Um oponente adjacente à escolha do mestre pode realizar um ataque imediato contra você.',
    22: 'Fome repentina: você tem duas rodadas para gastar uma ação padrão e comer alguma coisa substancial (como uma ração de viagem). Se não fizer isso, você sofre 2 pontos de dano em Constituição.',
    23: 'Visão profana: você vê uma aparição de um deus inimigo da sua divindade padroeira. Você fica desprevenido nesta rodada, e na próxima rodada sofre uma penalidade de –5 em todas as rolagens.',
    24: 'Um vento frio sopra em suas costas... Um fantasma? Uma maldição? Ou apenas o inverno? Não importa, você fica abalado por uma rodada.',
    25: 'Optando por garantir pelo menos um ataque bem-sucedido, na próxima rodada você deve usar o seu melhor ataque contra o oponente mais fraco no campo de visão.',
    26: 'Você tenta vencer o combate “no grito”. Na próxima rodada, você deve gastar uma ação padrão e usar a perícia Intimidação contra um oponente que já tenha atacado. Se for bem-sucedido em um teste contra CD 30, você deixa-o abalado.',
    27: 'Tomado por medo, indecisão ou outro sentimento qualquer, você trava! Na próxima rodada, você não pode agir, mas pode se defender normalmente.',
    28: 'Ato antiheroico: você faz algo indigno de um herói, como acovardar-se frente a um ataque, usar um inocente como escudo ou lutar sujo. Perca um ponto heroico.',
    29: 'Sua pistola explode na sua mão, e o tiro sai pela culatra! Você sofre 3d6 pontos de dano de fogo e sua arma fica inutilizada até ser consertada.',
    30: 'Sequência de desastres: seu próximo acerto crítico será substituído por uma falha crítica.',
    31: 'Rumo ao vazio: se você estiver a 1,5m de qualquer precipício ou queda, você agora está em queda livre.',
    32: 'Você se cansa de ser chamado de mago fracote, e vai mostrar que pode vencer uma luta com suas próprias mãos. Até o fim do combate, você não pode lançar magias.',
    33: 'Seu ataque rebate no oponente, atingindo você mesmo. Sofra metade do dano que causaria caso tivesse acertado.',
    34: 'Um rato enorme morde sua perna e você recebe as doenças febre do esgoto, enjoo cegante e tremores (Tormenta RPG, Capítulo 10). Estes efeitos só se manifestam depois de um dia.',
    35: 'Calafrio: um espírito ou alma penada passa perto de você e deixa-o muito nervoso. Você fica abalado por 1d4 rodadas.',
    36: 'Dor de cabeça súbita: penalidade de –4 em testes de Vontade até o fim do combate.',
    37: 'Má decisão: quem nunca tomou? O mestre escolhe o alvo e tipo do seu próximo ataque. Contudo, você atacará um inimigo, não um aliado.',
    38: 'Enjoo súbito! Tanto sangue revira seu estômago. Você fica enjoado por 1d4 rodadas.',
    39: 'Você nota algo muito interessante do outro lado do campo de batalha. Na próxima rodada, você deve usar uma ação completa para se movimentar.',
    40: 'Você faz uma bobagem enorme e mostra que não é tão poderoso assim. Seus oponentes ficam motivados, recebendo +1 nas jogadas de ataque contra você.',
    41: 'Cãibra na perna direita: seu deslocamento é reduzido à metade. Caso você não tenha a perna esquerda, cai no chão. Se estiver na água, sofre –4 em testes para nadar.',
    42: 'Mil maldições! Uma maldição itinerante chega até você. Você sofre uma penalidade de –4 em todas as rolagens por 4 rodadas. Depois disso, o aliado mais próximo de você sofre esta mesma maldição por 4 rodadas, e assim sucessivamente. A maldição não pode ocorrer duas vezes na mesma pessoa no mesmo dia.',
    43: 'Seu elmo gira e tapa sua visão! Você está cego até a próxima rodada, quando então deve usar uma ação de movimento para colocá-lo no lugar ou continuar cego. Se você não estiver usando um elmo, outro elemento tapa sua visão, mas você ainda fica cego até gastar uma ação de movimento para desfazer o que quer que seja.',
    44: 'Um cisco entra no seu olho! Você fica cego por 1d4 rodadas.',
    45: 'Sua arma desgasta-se com o golpe, quebrando-se, a menos que seja obra-prima ou magistral. Neste caso, ela impõe uma penalidade de –1 em todas as jogadas de ataque até ser consertada.',
    46: 'Você decide tentar uma técnica de defesa inovadora, que acaba de inventar. Infelizmente, ela não é muito eficaz. Você sofre uma penalidade de –2 na CA por 1d4 rodadas.',
    47: 'Subitamente, você nota que está fora de forma, e que todas aquelas noites na taverna estão cobrando seu preço. Você fica fatigado até o fim do combate.',
    48: 'Que combate tedioso! Você para de prestar atenção a seus oponentes e começa a examinar seus arredores. Você fica desprevenido por 1d4 rodadas, mas pode fazer um teste de Percepção (CD 20) como uma ação livre. Se for bem-sucedido, o mestre pode lhe fornecer alguma informação.',
    49: 'Sua aljava ou cartucheira cai no chão, e suas flechas, virotes ou balas se espalham. Sempre que quiser recarregar sua arma, você deve gastar uma ação de movimento para recolher a munição.',
    50: 'Um ratinho morde seu calcanhar. Você recebe a doença febre do esgoto (Tormenta RPG, Capítulo 10). Este efeito só se manifesta depois de um dia.',
    51: 'Seu cinto solta-se e suas calças caem! Perca uma ação de movimento para puxá-las de volta ou lute deste jeito indigno. Se você lutar com elas caídas, seu deslocamento é reduzido à metade e você não pode correr ou fazer investidas.',
    52: 'Você tropeça e desequilibra-se. Penalidade de –2 na CA até sua próxima rodada.',
    53: 'Sorvedouro de magia: devido a algum fenômeno arcano imprevisível, você perde 1d10 PM.',
    54: 'Derrame: uma súbita pontada seguida de dor de cabeça... Tudo fica preto. Será o fim? Faça um teste de Sabedoria contra CD 10. Em caso de sucesso, você sofre 1 ponto de dano em Sabedoria. Em caso de falha, você morre.',
    55: 'Um trovão ressoa bem na hora do seu golpe, assustando-o. Na próxima rodada você estará desprevenido.',
    56: 'O que você está esperando? Sonhando acordado, você sofre uma penalidade de –10 na ordem de iniciativa, pelo resto do combate. Isto pode mudar quando você age a partir da próxima rodada.',
    57: 'Raiva aleatória: você entra em fúria, como um bárbaro de 1° nível. Se já estiver em fúria, a sua fúria acaba.',
    58: 'Golpe nos olhos: se você sofrer um acerto crítico neste combate, seus olhos inundam-se de sangue, ou seus globos oculares saltam para fora das órbitas. Seja como for, você fica cego até receber uma cura maior.',
    59: 'Uma onda de energia positiva atinge o campo de batalha, mas só do lado dos inimigos... Todos os adversários recuperam 3d6 pontos de vida.',
    60: 'Pontada no peito: penalidade de –4 em testes de Fortitude até o fim do combate.',
    61: 'Uma mão esquelética surge do chão e puxa seu pé. Você fica agarrado. Para se soltar, precisa gastar uma ação padrão e fazer um teste de manobra oposto com a mão, que tem bônus +6.',
    62: 'Seu sangue esquenta e você se enfurece. Sofre 2 pontos de dano em Sabedoria e, na próxima rodada, deve fazer um ataque corpo-a-corpo (ou se esforçar para isso, aproximando-se de um inimigo, por exemplo).',
    63: 'Ferimentos antigos voltam a incomodar... Você sofre 1 ponto de dano não letal por nível de personagem.',
    64: 'Hã? Uma cor bonita, um pássaro interessante ou um pensamento capturam toda a sua atenção. Faça um teste de Sabedoria contra CD 10. Em caso de falha, você perde toda a sua próxima rodada. O quê?',
    65: 'O sol, uma magia ou uma tocha nas proximidades atrapalham sua visão: penalidade de –4 em testes de Reflexos até o fim do combate.',
    66: 'Você bate com o mindinho em algo, e é tomado por agonia! Ui! Não pode usar ataques desarmados durante a próxima rodada e sofre 2 pontos de dano em Destreza.',
    67: 'Você se engasga com poeira. Perca a rodada tossindo e sofra 2 pontos de dano em Constituição.',
    68: 'Você é tomado pela raiva da batalha e para de pensar direito. Sofra 2 pontos de dano de Inteligência e não use nenhuma habilidade especial (de classe, de raça, de talento...) na próxima rodada.',
    69: 'Ataque cardíaco: argh! Dor no peito, falta de ar, braço direito inutilizado por 1d6 rodadas. Faça um teste de Constituição contra CD 10. Em caso de sucesso, você sofre 1 ponto de dano em Constituição. Em caso de falha, você morre.',
    70: 'Compulsão autopreservativa: na próxima rodada você deve usar uma poção, magia, talento ou habilidade que restaure PV ou PM.',
    71: 'Este último golpe foi mais forte do que parecia! Você sofre de novo o dano do último golpe ou magia que atingiu-o, como dano não letal.',
    72: 'Um inseto entra na sua orelha bem no momento do golpe. Perca sua próxima ação de movimento para remover o incômodo ou sofra uma penalidade de –2 em jogadas de ataque até ele ir embora, em 2d4 rodadas.',
    73: 'Você termina o seu golpe com uma pose de grande efeito teatral, mas baixa qualidade combativa. Você fica desprevenido até o fim de sua próxima rodada.',
    74: 'Sua granada ou item de arremesso cai sem força perto do seu alvo, mas não explode ou ativa-se. O alvo deve fazer um teste de Reflexos contra CD 15, como uma ação livre. Em caso de sucesso, ele consegue chutar a granada ou item de arremesso de volta para você. Você então sofre os efeitos da arma!',
    75: 'Sua bolsa de moedas voa longe e espalha todo o seu ouro pelo chão. Tomara que você vença o combate e não precise fugir.',
    76: 'Ops! Faça um ataque imediato contra um de seus aliados. Seu aliado está desprevenido (penalidade de –4 na CA) contra este ataque.',
    77: 'Energia dissipada: se você usou seu ataque em conjunto com uma habilidade especial que tenha usos diários (como grito de kiai ou destruir o mal), perde todos os seus usos diários da habilidade.',
    78: 'Escorregão! Nada grave, a menos que você esteja lutando na beira de um precipício ou assemelhado. Neste caso, faça um teste de Reflexos contra CD 20 ou caia do precipício.',
    79: 'Sua granada ou item que você estava prestes a arremessar explode em sua mão. Sofra o efeito do item.',
    80: 'Você decide tentar fazer amizade com o inimigo. Na próxima rodada, você deve usar a perícia Diplomacia contra um oponente que você já tenha atacado. Se for bem-sucedido em um teste contra CD 30, ele desiste do combate (caso você e seus aliados estejam vencendo) ou aceita sua rendição (caso você e seus aliados estejam perdendo).',
    81: 'Uma poção ou frasco de produto alquímico que você carrega se quebra. Perca o item e sofra o efeito de um ataque com o item afetado (apenas se for um item de ataque). O mestre decide qual poção ou item é afetado.',
    82: 'Fogo amigo: você acerta um aliado que esteja lutando em corpo-a-corpo com o alvo original do seu ataque.',
    83: 'Uma cobra venenosa morde seu pé. Você sofre 1d12 pontos de dano.',
    84: 'Bobagem suprema: você tropeça e cai de mau jeito, torcendo o tornozelo e correndo o risco de quebrar o pescoço! Faça um teste de Destreza contra CD 10. Em caso de sucesso, você sofre 1 ponto de dano em Destreza. Em caso de falha, você quebra o pescoço e morre.',
    85: 'Tiro no pé — literalmente! Você causa o dano de um ataque com sua arma de disparo em si mesmo e fica com metade do deslocamento até receber uma cura maior.',
    86: 'Você chuta uma pedra! Seu pé fica doendo e seu deslocamento é reduzido à metade até o fim do combate.',
    87: 'Seu movimento com o ataque foi forte demais, e sua arma voa longe. Ela cai a 6m de você, em um ponto decidido pelo mestre.',
    88: 'Pessimismo súbito: mesmo que o combate esteja indo bem, você sente-se derrotado e inútil. Você fica abalado até o fim do combate.',
    89: 'Você tem uma tontura súbita e forte. Penalidade de –8 na CA até sua próxima rodada.',
    90: 'Sua mochila se abre e espalha todos os seus itens no chão, em um raio de 3m. Agora seus inimigos podem ver o que você carrega! Talvez algum deles decida pegar algo e sair correndo...',
    91: 'Você puxa demais a corda do seu arco ou besta! Ela se rompe, inutilizando a arma até ser consertada.',
    92: 'A tocha ou lampião que você carrega subitamente se apaga.',
    93: 'Cãibra no braço esquerdo: você deixa cair o que está segurando neste braço. Não pode fazer ataques desarmados ou segurar nada com a mão esquerda por 1d4 rodadas. Criaturas aladas que estejam voando (sem ajuda de magia) caem por 1d4 rodadas.',
    94: 'Você se distrai e abaixa sua guarda. Penalidade de –4 na CA até sua próxima rodada.',
    95: 'Tentando atingir mais longe que deveria, você distende o braço. Sofre –2 nas jogadas de ataque na próxima rodada e 2 pontos de dano em Força.',
    96: 'Cãibra no braço direito: você deixa cair o que está segurando neste braço. Não pode fazer ataques desarmados ou segurar nada com a mão direita por 1d4 rodadas. Criaturas aladas que estejam voando (sem ajuda de magia) caem por 1d4 rodadas.',
    97: 'Um meteoro está singrando os céus. Parece estar se aproximando... Oh não, está vindo direto para você! Você sofre 6d6 pontos de dano de esmagamento e 6d6 pontos de dano de fogo (Ref CD 25 reduz ambos à metade).',
    98: 'Você tropeça em sua própria na capa, calça ou saia: cai no chão e sofre 1d6 pontos de dano.',
    99: 'Zupt! A lâmina de sua espada ou machado, cabeça de seu martelo, etc., solta-se e voa para longe. A arma está inutilizada pelo resto do combate. Você deve consertar sua arma para poder usá-la de novo.',
    100: 'Visão divina: você vê uma aparição de seu deus patrono. Você fica desprevenido nesta rodada, mas na próxima rodada recebe um bônus de +5 em todas as rolagens.'


    };

    // Obtém a frase correspondente ao resultado
    var frase = frases[resultado];

    // Exibe o resultado na página
    document.getElementById('resultado').innerHTML = 'Resultado: ' + resultado + '<br>' + 'Frase: ' + frase;
  }